import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { WorkspaceProvider } from "@/contexts/workspace-context";
import AppSidebar from "@/features/menus/app-sidebar";

export const metadata: Metadata = {
  title: "AI Form Builder",
  description: "Generated by create next app",
};

export default function AppLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <WorkspaceProvider>
            <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
                <main>
                    {children}
                </main>
            </SidebarInset>
            </SidebarProvider>
      </WorkspaceProvider>
    )
}
