import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Form Builder",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: {
    children: React.ReactNode;
}) {
    return (
        <main className="min-h-screen">
            {children}
        </main>
    );
}
