__all__ = ["schema"]

schema = {'title': 'Library Book Registration',
 'sections': [{'id': 'book_details',
   'label': 'Book Details',
   'fields': [{'id': 'title',
     'label': 'Book Title',
     'type': 'text',
     'required': True,
     'readonly': False,
     'validation': {'minLength': 1, 'maxLength': 255},
     'options': [],
     'ui': {'placeholder': 'Enter the title of the book'}},
    {'id': 'author',
     'label': 'Author',
     'type': 'text',
     'required': True,
     'readonly': False,
     'validation': {'minLength': 1, 'maxLength': 255},
     'options': [],
     'ui': {'placeholder': "Enter the author's name"}},
    {'id': 'isbn',
     'label': 'ISBN',
     'type': 'text',
     'required': True,
     'readonly': False,
     'validation': {'minLength': 10, 'maxLength': 13},
     'options': [],
     'ui': {'placeholder': 'Enter the ISBN number'}},
    {'id': 'publication_year',
     'label': 'Publication Year',
     'type': 'number',
     'required': False,
     'readonly': False,
     'validation': {'minValue': 1000, 'maxValue': 2100},
     'options': [],
     'ui': {'placeholder': 'Enter the year of publication'}},
    {'id': 'genre',
     'label': 'Genre',
     'type': 'select',
     'required': False,
     'readonly': False,
     'validation': {},
     'options': ['Fiction',
      'Non-Fiction',
      'Science Fiction',
      'Fantasy',
      'Mystery',
      'Biography',
      'History',
      'Children'],
     'ui': {'placeholder': 'Select the genre'}}]}]}